behavior_server:
  ros__parameters:
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    local_frame: world
    global_frame: world
    robot_base_frame: base

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: world
    robot_base_frame: base
    transform_tolerance: 0.1
    # default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"
    # default_nav_through_poses_bt_xml: replace/with/path/to/bt.xml
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    path_blackboard_id: path
    navigators: ['navigate_to_pose', 'navigate_through_poses']
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
      # - smoother_error_code, navigate_to_pose_error_code, navigate_through_poses_error_code, etc

controller_server:
  ros__parameters:
    odom_topic: /aft_mapped_to_init
    use_sim_time: False
    # controller_frequency: 5.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"

      # Trajectory
      # teb_autosize: true
      teb_autosize: 1.0
      dt_ref: 0.3
      dt_hysteresis: 0.1
      max_samples: 30
      global_plan_overwrite_orientation: true
      allow_init_with_backwards_motion: true
      max_global_plan_lookahead_dist: 1.0
      global_plan_viapoint_sep: -1.0
      global_plan_prune_distance: 1.0
      exact_arc_length: false
      feasibility_check_no_poses: 5
      publish_feedback: false

      # Robot
      max_vel_x: 0.3
      max_vel_x_backwards: 0.3
      max_vel_y: 0.3
      max_vel_theta: 0.6
      acc_lim_x: 0.1
      acc_lim_y: 0.1
      acc_lim_theta: 0.3
      min_turning_radius: 0.0

      footprint_model:
        # type: "circular"
        # radius: 0.17 # for type "circular"
        type: "polygon"
        vertices: "[[0.2, -0.15], [0.3, -0.03], [0.3, 0.03], [0.2, 0.15], [-0.3, 0.15], [-0.3, -0.15]]"

      # GoalTolerance
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05
      free_goal_vel: false
      complete_global_plan: true

      # Obstacles
      min_obstacle_dist: 0.3
      inflation_dist: 0.5
      include_costmap_obstacles: true
      costmap_obstacles_behind_robot_dist: 1.0
      obstacle_poses_affected: 15
      costmap_converter_plugin: ""
      costmap_converter_spin_thread: true
      costmap_converter_rate: 5.0

      # Optimization
      no_inner_iterations: 5
      no_outer_iterations: 4
      optimization_activate: true
      optimization_verbose: false
      penalty_epsilon: 0.1
      obstacle_cost_exponent: 4.0
      weight_max_vel_x: 2.0
      weight_max_vel_y: 2.0
      weight_max_vel_theta: 1.0
      weight_acc_lim_x: 1.0
      weight_acc_lim_y: 1.0
      weight_acc_lim_theta: 1.0
      weight_kinematics_nh: 100.0
      weight_kinematics_forward_drive: 0.1
      weight_kinematics_turning_radius: 0.01
      weight_optimaltime: 60.0
      weight_shortest_path: 0.01
      weight_obstacle: 60.0
      weight_inflation: 0.2
      weight_dynamic_obstacle: 10.0
      weight_dynamic_obstacle_inflation: 0.2
      weight_viapoint: 1.0
      weight_adapt_factor: 2.0

      # Homotopy Class Planner
      enable_homotopy_class_planning: true
      enable_multithreading: true
      max_number_classes: 4
      selection_cost_hysteresis: 1.0
      selection_prefer_initial_plan: 0.9
      selection_obst_cost_scale: 1.0
      selection_alternative_time_cost: false
      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5.0
      roadmap_graph_area_length_scale: 1.0
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_heading_threshold: 0.45
      switching_blocking_period: 0.0
      viapoints_all_candidates: true
      delete_detours_backwards: true
      max_ratio_detours_duration_best_duration: 3.0
      visualize_hc_graph: false
      # visualize_with_time_as_z_axis_scale: false
      visualize_with_time_as_z_axis_scale: 0.0

      # Recovery
      shrink_horizon_backup: true
      shrink_horizon_min_duration: 10.0
      oscillation_recovery: true
      oscillation_v_eps: 0.1
      oscillation_omega_eps: 0.1
      oscillation_recovery_min_duration: 10.0
      oscillation_filter_duration: 10.0


# 全局代价地图配置
global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: world
      robot_base_frame: base
      update_frequency: 5.0
      publish_frequency: 5.0
      resolution: 0.1
      transform_tolerance: 0.5
      robot_radius: 0.2
      rolling_window: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        # map_subscribe_transient_local: True
        enabled: true
        # subscribe_to_updates: true
        # transform_tolerance: 0.1
        map_topic: /map

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        track_unknown_space: true
        footprint_clearing_enabled: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.0
        raytrace_max_range: 4.0
        raytrace_min_range: 0.0
        # max_obstacle_height: 2.0
        combination_method: 1
        observation_sources: scan
        scan:
          topic: /cloud_registered
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 4.0
          raytrace_min_range: 0.0
          # max_obstacle_height: 2.0
          # min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 5.0
        cost_scaling_factor: 3.0
        # inflate_unknown: false
        # inflate_around_unknown: true
      # always_send_full_costmap: True

      # static_layer:
      #   plugin: "nav2_costmap_2d::StaticLayer"
      #   enabled: true
      #   map_topic: "/map"

      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: true
      #   obstacle_range: 3.0
      #   raytrace_range: 4.0
      #   track_unknown_space: true
      #   combination_method: 1
      #   observation_sources: laser_scan_sensor
      #   laser_scan_sensor:
      #     data_type: LaserScan
      #     topic: scan
      #     marking: true
      #     clearing: true

      # inflation_layer:
      #   plugin: "nav2_costmap_2d::InflationLayer"
      #   enabled: true
      #   inflation_radius: 0.2
      #   cost_scaling_factor: 3.0

# 局部代价地图配置
local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: world
      robot_base_frame: base
      update_frequency: 5.0
      publish_frequency: 5.0
      resolution: 0.05
      transform_tolerance: 0.5
      robot_radius: 0.2
      rolling_window: true
      width: 3
      height: 3
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        # map_subscribe_transient_local: True
        enabled: true
        # subscribe_to_updates: true
        # transform_tolerance: 0.1
        map_topic: /map

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        track_unknown_space: true
        footprint_clearing_enabled: true
        obstacle_max_range: 3.0
        obstacle_min_range: 0.0
        raytrace_max_range: 4.0
        raytrace_min_range: 0.0
        # max_obstacle_height: 2.0
        combination_method: 1
        observation_sources: scan
        scan:
          topic: /cloud_registered
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 4.0
          raytrace_min_range: 0.0
          # max_obstacle_height: 2.0
          # min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 5.0
        cost_scaling_factor: 3.0
        # inflate_unknown: false
        # inflate_around_unknown: true

      # static_layer:
      #   plugin: "nav2_costmap_2d::StaticLayer"
      #   enabled: true
      #   map_topic: "/map"

      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: true
      #   obstacle_range: 3.0
      #   raytrace_range: 4.0
      #   track_unknown_space: true
      #   combination_method: 1
      #   observation_sources: laser_scan_sensor
      #   laser_scan_sensor:
      #     data_type: LaserScan
      #     topic: scan
      #     marking: true
      #     clearing: true

      # inflation_layer:
      #   plugin: "nav2_costmap_2d::InflationLayer"
      #   enabled: true
      #   inflation_radius: 0.15
      #   cost_scaling_factor: 5.0